/**
 * Каталог Капсула — товары и фото с lime-shop.com (личный просмотр).
 * Размеры: scripts/enrich-product-sizes.mjs
 */
function u(url) {
  return url;
}

const WOMEN = [
  {
    id: "lime-women-34779",
    gender: "women",
    title: "Мини-платье ципао из хлопка и льна",
    category: "Платья",
    price: 6999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/007e5d1dba675fb79d6eef562c7c04ca.jpeg"),
    description: "Приталенное платье мини из микса хлопка и льна с застежкой в азиатском стиле клевант. Воротник-стойка. Короткие рукава. На хлопковой подкладке. Фактическая застежка молнией на спине.",
    sizeChart: "women_clothing",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "lime-women-33734",
    gender: "women",
    title: "Хлопковое платье-рубашка с вышивкой",
    category: "Платья",
    price: 6999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/f1773dd4f6b753e7bb778fc3c210caef.jpeg"),
    description: "Приталенное платье миди из хлопка с минималистичной вышивкой на левой стороне груди. Отложной воротник и открытый вырез. Длинные рукава с манжетами. Эластичный пояс. Пышный подол клеш. Застежка на пуговицы.",
    sizeChart: "women_clothing",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "lime-women-33981",
    gender: "women",
    title: "Джинсы с отделкой перламутровым жемчугом",
    category: "Джинсы",
    price: 5999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/4f9bfda5d7335b16841ef4a33ce356ee.jpeg"),
    description: "Прямые джинсы со средней посадкой из хлопкового денима. Эффект винтажной потертости. Отделка перламутровыми бусинами под жемчуг вдоль боковых швов. Пять карманов. Застежка на молнию и металлическую пуговицу-болт.",
    sizeChart: "women_bottoms",
    sizes: ["34", "36", "38", "40", "42"],
  },
  {
    id: "lime-women-30591_3460_816",
    gender: "women",
    title: "Прямые джинсы со средней посадкой",
    category: "Джинсы",
    price: 4599,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/27594088a29d5e09a959bfcec2820854.jpeg"),
    description: "Джинсы прямого кроя со средней посадкой из хлопкового денима. Пять карманов. Застежка на молнию и металлическую пуговицу-болт.",
    sizeChart: "women_bottoms",
    sizes: ["34", "36", "38", "40", "42"],
  },
  {
    id: "lime-women-34107",
    gender: "women",
    title: "Прямые брюки из лиоцелла и льна",
    category: "Брюки",
    price: 6599,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/85006b446a67599397dbe794effb57e9.jpeg"),
    description: "Брюки прямого кроя из ткани на основе лиоцелла и льна. Передние карманы и декоративные карманы сзади. Застежка на молнию, крючок и внутреннюю пуговицу.",
    sizeChart: "women_bottoms",
    sizes: ["34", "36", "38", "40", "42"],
  },
  {
    id: "lime-women-32550_7780_973",
    gender: "women",
    title: "Брюки из лиоцелла и льна",
    category: "Брюки",
    price: 5999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/c3c17bc56e865251b0c8dccacc637a91.jpeg"),
    description: "Брюки прямого кроя из лиоцелла и льна со складками спереди. Боковые карманы на бедрах и декоративные карманы сзади. Застежка на молнию, крючок и внутреннюю пуговицу.",
    sizeChart: "women_bottoms",
    sizes: ["34", "36", "38", "40", "42"],
  },
  {
    id: "lime-women-33467",
    gender: "women",
    title: "Мини-юбка объемного кроя с оборкой",
    category: "Юбки",
    price: 4599,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/00eac37393cf580cb80087bf3ba0168d.jpeg"),
    description: "Мини-юбка на синтепоне для создания объемного кроя «тюльпан». Декорирована оборкой из полупрозрачной органзы по низу. На подкладке. Застежка на незаметную молнию.",
    sizeChart: "women_skirts",
    sizes: ["34", "36", "38", "40", "42"],
  },
  {
    id: "lime-women-33624_6939_189",
    gender: "women",
    title: "Хлопковая юбка с цветочным принтом",
    category: "Юбки",
    price: 3999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/0e0827ca8fcd57b59008100114b19f54.jpeg"),
    description: "Юбка миди из хлопка с цветочным мотивом. Дополненная оборкой по низу модель застегивается молнией. На легкой подкладке из тонкого хлопка.",
    sizeChart: "women_skirts",
    sizes: ["34", "36", "38", "40", "42"],
  },
  {
    id: "lime-women-32835_6043_129",
    gender: "women",
    title: "Футболка поло из эластичного пике́ с вышивкой",
    category: "Футболки и топы",
    price: 2999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/c9deb976c46e5bdfa6021ad3b4e68768.jpeg"),
    description: "Прямая футболка из смесового хлопка с добавлением эластана. Вышивка в стиле морского спорта на левой стороне груди. Отложной воротник. Короткие рукава. Боковые разрезы. Застежка пуговицами на короткой планке в стиле поло.",
    sizeChart: "women_clothing",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "lime-women-34243",
    gender: "women",
    title: "Хлопковая футболка с принтом",
    category: "Футболки и топы",
    price: 1999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/dfcad4a993e255d396babbc42e90a14d.jpeg"),
    description: "Свободная футболка из мягкого хлопкового джерси. Контрастный принт в летней тематике. Круглый вырез. Короткие рукава.",
    sizeChart: "women_clothing",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "lime-women-34615",
    gender: "women",
    title: "Топ из вискозы с бретелями из цепочек",
    category: "Футболки и топы",
    price: 4999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/bd09e403ac45529f8ff5c58ce6027bd0.jpeg"),
    description: "Топ из тонкого трикотажа с мягкими волокнами вискозы. Модель с открытыми плечами и спиной акцентирована тонкими бретелями из золотистых цепочек.",
    sizeChart: "women_clothing",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "lime-women-32526_6300_585",
    gender: "women",
    title: "Хлопковый топ кружевной вязки кроше",
    category: "Футболки и топы",
    price: 5999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/6b39e667c3795d5fb8bc995346ad1a82.jpeg"),
    description: "Приталенный топ из хлопкового кружева плетения кроше с узорами в виде цветов. Дополненная фестончатой отделкой модель с воротником-стойкой застегивается обтяжными пуговицами сзади.",
    sizeChart: "women_clothing",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "lime-women-34758",
    gender: "women",
    title: "Рубашка ципао изо льна и вискозы",
    category: "Блузки и рубашки",
    price: 5999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/f8b677bae0c95a068d769c0c26577e20.jpeg"),
    description: "Свободная рубашка с лацканами, длинными рукавами и застежкой клевант, позаимствованной от костюмов Азии. Модель выполнена из легкой ткани на основе льна и вискозы.",
    sizeChart: "women_clothing",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "lime-women-24827_5503_844",
    gender: "women",
    title: "Рубашка прямого кроя из 100% льна",
    category: "Блузки и рубашки",
    price: 5599,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/6bc0076388aa55219da2ff36dace8967.jpeg"),
    description: "Рубашка прямого кроя из 100% льна. Отложной воротник. Длинные рукава с манжетами. Закругленный нижний край. Прямоугольная складка на спине. Застежка на пуговицы.",
    sizeChart: "women_clothing",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "lime-women-34028",
    gender: "women",
    title: "Приталенный блейзер ципао из лиоцелла и льна",
    category: "Пиджаки и жилеты",
    price: 8999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/fe65e81a602355909735cd1821258d63.jpeg"),
    description: "Приталенный блейзер из костюмной ткани на основе лиоцелла и льна. Детализирован воротником-стойкой и короткими рукавами. На подкладке. Застегивается на плетеные пуговицы в стиле национальных костюмов Азии.",
    sizeChart: "women_clothing",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "lime-women-34027",
    gender: "women",
    title: "Блейзер ципао изо льна и хлопка",
    category: "Пиджаки и жилеты",
    price: 8999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/9cb89fd652a85029adc5850a7c015d2b.jpeg"),
    description: "Приталенный блейзер изо льна, хлопка и вискозы. Детализирован воротником-стойкой и короткими рукавами. На подкладке. Ретро застежка клевант на пуговицы с петлями.",
    sizeChart: "women_clothing",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "lime-women-25426_5379_749",
    gender: "women",
    title: "Кардиган из хлопка с интарсией",
    category: "Трикотаж",
    price: 5999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/3ed503b43eac50bfb258ba8cfc2e47a9.jpeg"),
    description: "Ярким декором для кардигана оверсайз стал узор в технике интарсии. Модель с отложным воротником и короткими рукавами застегивается на пуговицы. Выполнен из смесового хлопка.",
    sizeChart: "women_clothing",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "lime-women-34418",
    gender: "women",
    title: "Хлопковый кардиган из кроше",
    category: "Трикотаж",
    price: 7999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/dd6b8fddaa7853a6900893c254a5e226.jpeg"),
    description: "Кардиган сплетен хлопковой нитью в ремесленной технике создания кружева кроше. Однотонная модель с воротником и длинными рукавами застегивается обтяжными пуговицами.",
    sizeChart: "women_clothing",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "lime-women-33007",
    gender: "women",
    title: "Джинсовая куртка из хлопка и волокон конопли",
    category: "Верхняя одежда",
    price: 7999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/f3cd66e4c0ba5827afdf85fefc79f784.jpeg"),
    description: "Альтернатива на летний сезон. Приталенная куртка, напоминающая рубашку на запа́х, из хлопкового денима с лиоцеллом и волокнами конопли. Заостренный вырез. Длинные рукава. Накладные карманы. Фиксируется поясом.",
    sizeChart: "women_clothing",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "lime-women-31916_2910_478",
    gender: "women",
    title: "Удлиненная куртка оверсайз",
    category: "Верхняя одежда",
    price: 11999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/a839ae81d2d5530e9e1e0f3352d6ed69.jpeg"),
    description: "Удлиненная куртка оверсайз с воротником-стойкой и длинными рукавами. Регулируемый пояс на корд-системе с фиксаторами. Передние карманы на молния. На подкладке. Застегивается на двустороннюю молнию.",
    sizeChart: "women_clothing",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "lime-women-34428",
    gender: "women",
    title: "Шорты-боксеры из хлопка с принтом",
    category: "Шорты",
    price: 2599,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/9bde45175abb5ac6bd2f943e6ff100ea.jpeg"),
    description: "Широкие шорты мини из хлопкового футера. Контрастная отделка. Принт на левой стороне. Регулируемый пояс на кулиске. Передние карманы и закругленные вырезы по низу.",
    sizeChart: "women_bottoms",
    sizes: ["34", "36", "38", "40", "42"],
  },
  {
    id: "lime-women-32811_4454_851",
    gender: "women",
    title: "Шорты-боксеры с вышивкой",
    category: "Шорты",
    price: 2599,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/095c29fff137553dae36d6c7b5bc3038.jpeg"),
    description: "Широкие шорты мини из смесового хлопка. Контрастная отделка. Вышивка на левой стороне. Регулируемый пояс на кулиске. Передние карманы и накладной карман сзади.",
    sizeChart: "women_bottoms",
    sizes: ["34", "36", "38", "40", "42"],
  },
  {
    id: "lime-women-26350_8957_133",
    gender: "women",
    title: "Ультратонкие легинсы",
    category: "Леггинсы",
    price: 999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/227a8c5dad4e5f58902a90900f939fe1.jpeg"),
    description: "Матовые легинсы плотностью 60 ден из эластичной ткани на основе полиамида. Широкий пояс. Плоские швы, не натирающие кожу. Изделие плотно облегает фигуру и не сковывает движения. *Изделие относится к категории нижнее белье.",
    sizeChart: "women_bottoms",
    sizes: ["34", "36", "38", "40", "42"],
  },
  {
    id: "lime-women-29637_1713_233",
    gender: "women",
    title: "Колготки-легинсы со штрипками",
    category: "Леггинсы",
    price: 999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/49402ef3543253bb96ec035342326bdd.jpeg"),
    description: "Гибридная модель колготок с открытой стопой выполнена из шелковистого полиамида плотностью 50 ден. Оформлены штрипками. Классическая посадка. Плоские швы. Обладают легким моделирующим эффектом. *Изделие относится к категории нижнее белье.",
    sizeChart: "women_bottoms",
    sizes: ["34", "36", "38", "40", "42"],
  },
  {
    id: "lime-women-34126",
    gender: "women",
    title: "Блейзер из лиоцелла и льна с корсетной шнуровкой",
    category: "Костюмы",
    price: 9999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/24703814730c50bfb1d7f5ed11fa3ef7.jpeg"),
    description: "Однобортный блейзер из лиоцелла, льна и хлопка. Приталенный крой оформлен корсетной шнуровкой на спине. Шалевый воротник. Короткие рукава. Подплечники реглан. Передние карманы. На подкладке. Застежка на обтяжные пуговицы.",
    sizeChart: "women_clothing",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "lime-women-34127",
    gender: "women",
    title: "Брюки и лиоцелла и льна со складками",
    category: "Костюмы",
    price: 6599,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/c52e1fa62d0f567ebc0b4ebf9fe68a5e.jpeg"),
    description: "Объемные брюки из лиоцелла, льна и хлопка. Дополнены симметричными складками под поясом. Передние карманы и декоративные карманы сзади. Регулируемые манжеты на обтяжных пуговицах. Застежка на молнию, крючок и внутреннюю пуговицу.",
    sizeChart: "women_clothing",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "lime-women-33626_5060_299",
    gender: "women",
    title: "Босоножки в цвете металлик на каблуке",
    category: "Обувь",
    price: 8999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/5243a7f710fa571f81dec431afc67470.jpeg"),
    description: "Легкая пара босоножек в цвете металлик на каблуке. Узкие ремешки на подъеме. Открытый мыс острой формы. Застежка на ремешок с пряжкой на щиколотке. В комплект входит пыльник. Высота каблука: 6,6 см",
    sizeChart: "women_shoes",
    sizes: ["36", "37", "38", "39", "40", "41"],
  },
  {
    id: "lime-women-31217_2120_034",
    gender: "women",
    title: "Босоножки из овечьей кожи на каблуке",
    category: "Обувь",
    price: 10999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/d23cbda7fe3654409cc7cbb5497df0c9.jpeg"),
    description: "Полностью выполненные босоножки из овечьей кожи на каблуке. Металлизированный финиш золотого цвета. Узкие ремешки на подъеме. Зауженный мыс. Застежка на ремешок с пряжкой на щиколотке. В комплект входит пыльник. Высота каблука: 7 см",
    sizeChart: "women_shoes",
    sizes: ["36", "37", "38", "39", "40", "41"],
  },
  {
    id: "lime-women-33689",
    gender: "women",
    title: "Сандалии-слайдеры из винила",
    category: "Обувь",
    price: 2999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/00189063d93c523980d48ca57e6801bf.jpeg"),
    description: "Сандалии-слайдеры из полупрозрачного гибкого винила. Открытый мыс круглой формы. В комплект входит пыльник.",
    sizeChart: "women_shoes",
    sizes: ["36", "37", "38", "39", "40", "41"],
  },
  {
    id: "lime-women-32672_6430_160",
    gender: "women",
    title: "Сандалии-слайдеры",
    category: "Обувь",
    price: 2999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/917f965e7b0c542f93effe7423de3e22.jpeg"),
    description: "Сандалии-слайдеры из полупрозрачной гибкой резины. Открытый мыс круглой формы. В комплект входит пыльник.",
    sizeChart: "women_shoes",
    sizes: ["36", "37", "38", "39", "40", "41"],
  },
  {
    id: "lime-women-34318",
    gender: "women",
    title: "Плетеная сумка на молнии",
    category: "Сумки",
    price: 6999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/7844dd413b445047ba86de547d72c8bd.jpeg"),
    description: "Мягкая сумка из переплетенных полос ткани под кожу, которые формируют клетчатый узор. Короткая ручка. Съемный ремень для ношения через плечо. Одно отделение с карманом. На текстильной подкладке в тон. Застежка на молнию. Размер: 18,5 х 11 х 14 см (длина х ширина х высота).",
    sizeChart: "one_size",
    sizes: ["One size"],
  },
  {
    id: "lime-women-32687_5614_016",
    gender: "women",
    title: "Плетеная сумка",
    category: "Сумки",
    price: 6999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/0629fd6fb64c556898013b0ad31226c8.jpeg"),
    description: "Мягкая сумка из переплетенных полос ткани под гладкую кожу, которые формируют клетчатый узор. Плетеная плечевая ручка. Вместительное основное отделение. Размер: 32 х 7 х 15 см (длина х ширина х высота).",
    sizeChart: "one_size",
    sizes: ["One size"],
  },
  {
    id: "lime-women-33993",
    gender: "women",
    title: "Хлопковая косынка вязки кроше",
    category: "Аксессуары",
    price: 3599,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/f7deda8313a25bd3a20a8aa6c542aa97.jpeg"),
    description: "Треугольная косынка-платок из хлопка кружевной вязки кроше. ЕДИНЫЙ РАЗМЕР: 164 x 39 см",
    sizeChart: "one_size",
    sizes: ["One size"],
  },
  {
    id: "lime-women-34548",
    gender: "women",
    title: "Платок-косынка из хлопка с вышивкой",
    category: "Аксессуары",
    price: 2999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/27ae5a0a91995bfb9d5468f8774060c7.jpeg"),
    description: "Платок треугольной формы из хлопка с фактурной вышивкой бродери англэз и тесьмой.",
    sizeChart: "one_size",
    sizes: ["One size"],
  },
];

const MEN = [
  {
    id: "lime-men-32925",
    gender: "men",
    title: "Футболка из хлопка с принтом",
    category: "Футболки и поло",
    price: 2599,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/9b06801a88e25c1dbf9fa008fa196fb8.jpeg"),
    description: "Футболка прямого кроя из хлопкового джерси. Дополнена контрастным принтом спереди и на спине. Круглый вырез. Короткие рукава.",
    sizeChart: "men_clothing",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "lime-men-32087_5771_544",
    gender: "men",
    title: "Футболка из хлопка с принтом",
    category: "Футболки и поло",
    price: 3599,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/c9aac62f0280527f81e59cde16d11a93.jpeg"),
    description: "Футболка прямого кроя из хлопкового джерси. Контрастный принт спереди. Круглый вырез. Короткие рукава.",
    sizeChart: "men_clothing",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "lime-men-33668",
    gender: "men",
    title: "Футболка поло из пике́",
    category: "Футболки и поло",
    price: 2999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/f2091f6c32b05fa2bf3e99d60067133c.jpeg"),
    description: "Базовая модель поло выполнена из фактурного пике́ на основе смесового хлопка. Прямой крой с отложным воротником и короткими рукавами. Застежка на пуговицы на планке.",
    sizeChart: "men_clothing",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "lime-men-22640_3677_255",
    gender: "men",
    title: "Футболка поло из пике́",
    category: "Футболки и поло",
    price: 2999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/7cedaa3c0bbb5ae68b59274b3330ce12.jpeg"),
    description: "Базовая модель поло выполнена из фактурного пике́ на основе хлопка. Прямой крой с отложным воротником и короткими рукавами. Застежка на пуговицы на планке.",
    sizeChart: "men_clothing",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "lime-men-33956",
    gender: "men",
    title: "Рубашка из 100% льна с лацканами",
    category: "Рубашки",
    price: 8999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/e652993340ef5fab8383be54f3c53413.jpeg"),
    description: "Рубашка прямого кроя из натуральной ткани на основе 100% льна. Английский воротник с лацканами. Длинные рукава. Накладной карман на груди. Застежка на пуговицы.",
    sizeChart: "men_clothing",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "lime-men-33572",
    gender: "men",
    title: "Рубашка изо льна и хлопка с карманами",
    category: "Рубашки",
    price: 8999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/4e17cbf2d5975c03a836380ac1e90f00.jpeg"),
    description: "Рубашка из натуральной ткани на основе льна и хлопка. Модель свободного кроя с отложным воротником и длинными рукавами дополнена накладными карманами с клапанами. Застежка на пуговицы.",
    sizeChart: "men_clothing",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "lime-men-25658_4355_216",
    gender: "men",
    title: "Зауженные джинсы из лиоцелла и хлопка",
    category: "Джинсы",
    price: 6999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/9fb29a7a667e525f83c1672e5fec652f.jpeg"),
    description: "Джинсы зауженного кроя выполнены из денима на основе лиоцелла и хлопка. Версия в классическом стиле костюмных брюк оформлена защипами под поясом. Передние карманы и накладные карманы сзади. Манжеты оформлены отворотами. Застежка на молнию и металлическую пуговицу.",
    sizeChart: "men_bottoms",
    sizes: ["46", "48", "50", "52", "54"],
  },
  {
    id: "lime-men-33423",
    gender: "men",
    title: "Зауженные джинсы из хлопка и лиоцелла",
    category: "Джинсы",
    price: 7999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/176cd868bd8d57c5b7ceef8598530c5e.jpeg"),
    description: "Прямые по длине и зауженные книзу джинсы из легкого денима на основе хлопка и лиоцелла. Средняя посадка оформлена эластичной вставкой на поясе. Акцентные защипы и стрелки. Передние карманы, накладные карманы сзади. Застежка на молнию и металлическую пуговицу.",
    sizeChart: "men_bottoms",
    sizes: ["46", "48", "50", "52", "54"],
  },
  {
    id: "lime-men-34340",
    gender: "men",
    title: "Брюки из хлопка с принтом",
    category: "Брюки",
    price: 4999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/743c9c759cc053989a9a50f4c6f95cf2.jpeg"),
    description: "Прямые брюки в спортивном стиле из хлопкового футера. Эластичный пояс, регулируемый шнурком. Передние карманы, один из которых дополнен принтом. Накладной карман сзади.",
    sizeChart: "men_bottoms",
    sizes: ["46", "48", "50", "52", "54"],
  },
  {
    id: "lime-men-27476_8230_804",
    gender: "men",
    title: "Зауженные брюки из хлопка",
    category: "Брюки",
    price: 6999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/2c0e21db39585bd195b9c73b5315530a.jpeg"),
    description: "Свободные в бедрах брюки с зауженными манжетами из хлопкового футера. Прошитые стрелки. Эластичный пояс на кулиске. Передние карманы. Дополненный застежкой на кнопку карман сзади.",
    sizeChart: "men_bottoms",
    sizes: ["46", "48", "50", "52", "54"],
  },
  {
    id: "lime-men-33522",
    gender: "men",
    title: "Джемпер поло из 100% льна",
    category: "Трикотаж",
    price: 6999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/7121c279e8165274a643b5f478236eef.jpeg"),
    description: "Джемпер с короткими рукавами из нежаркого трикотажа на основе льна. Отложной воротник. Застежка на пуговицы на планке.",
    sizeChart: "men_clothing",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "lime-men-33081_6762_002",
    gender: "men",
    title: "Джинсовая куртка из хлопка и льна",
    category: "Верхняя одежда",
    price: 11999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/0ad8b11b541d50a8bde35f6d6f7b5908.jpeg"),
    description: "Легкая куртка выполнена из денима на основе хлопка и льна. Ткань дополнена монохромным жаккардовым узором. Модель прямого кроя с отложным воротником и прорезными карманами. Один внутренний карман, вшитый в подкладочную ткань. Застегивается металлической молнией.",
    sizeChart: "men_clothing",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "lime-men-33418",
    gender: "men",
    title: "Джинсовая куртка с отложным воротником",
    category: "Верхняя одежда",
    price: 8999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/fa7f311bf9c85d899254a8982c0b2ac1.jpeg"),
    description: "Куртка из плотного денима на основе хлопка с контрастной изнаночной стороной. Модель прямого кроя с отложным воротником и передними карманами. Длинные рукава с манжетами. Регулируемые хлястики по бокам пояса. Застегивается металлической молнией.",
    sizeChart: "men_clothing",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "lime-men-34072",
    gender: "men",
    title: "Прямые шорты изо льна с защипами",
    category: "Шорты",
    price: 6999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/7415f0f2337052039f11b997e2479fa1.jpeg"),
    description: "Бермуды из 100% льна. Прямой крой с защипами и классическими стрелками. Эластичный пояс со шлевками для ремня регулируется шнурком. Передние карманы, прорезные карманы сзади. Застежка на молнию, внутреннюю и внешнюю пуговицы.",
    sizeChart: "men_bottoms",
    sizes: ["46", "48", "50", "52", "54"],
  },
  {
    id: "lime-men-33400",
    gender: "men",
    title: "Двубортный блейзер из 100% льна",
    category: "Пиджаки",
    price: 19999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/617dfbdefccf58978d1e526c62f7a2a9.jpeg"),
    description: "Блейзер приталенного кроя из легкой костюмной ткани на основе льна. Заостренные лацканы. Накладные передние карманы и карман с листочкой на груди. Внутренние карманы. Модель на подкладке из чистого хлопка, рукава дополнительно укреплены вискозной тканью. Двубортный фасон застежки",
    sizeChart: "men_clothing",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "lime-men-33398",
    gender: "men",
    title: "Двубортный блейзер из 100% льна в полоску",
    category: "Пиджаки",
    price: 15999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/877eb94086b754e9a7df6bcccb37aba8.jpeg"),
    description: "Блейзер классического прямого кроя из фактурной ткани в полоску на основе чистого льна. Заостренные лацканы. Передние карманы с клапанами и карман с листочкой на груди. Внутренние карманы. Модель на подкладке из хлопка, рукава дополнительно укреплены вискозной тканью. Двубортный ",
    sizeChart: "men_clothing",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "lime-men-34071",
    gender: "men",
    title: "Замшевые лоферы",
    category: "Обувь",
    price: 12999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/014846881a2e5e7b846a271dc293b78f.jpeg"),
    description: "Мягкие туфли из натуральной замши с узкой шнуровкой на союзке и по контуру выреза. Закругленный мыс миндалевидной формы дополнен фактурным швом. Кожаные стелька и подкладка. Прорезиненная подошва с широким каблуком. В комплект входит пыльник.",
    sizeChart: "men_shoes",
    sizes: ["40", "41", "42", "43", "44", "45", "46"],
  },
  {
    id: "lime-men-34068",
    gender: "men",
    title: "Замшевые сандалии",
    category: "Обувь",
    price: 12999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/a1594b85cc795b19a59d0b40dcac296f.jpeg"),
    description: "Замшевые сандалии на плоской подошве с легким принципом надевания без застежки. Широкие ремешки крест-накрест на подъеме. Круглый мыс. Стелька из основного материала. В комплект входит пыльник.",
    sizeChart: "men_shoes",
    sizes: ["40", "41", "42", "43", "44", "45", "46"],
  },
  {
    id: "lime-men-33393",
    gender: "men",
    title: "Сумка-шопер из замши с парными ручками",
    category: "Рюкзаки и аксессуары",
    price: 17999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/2ffa112533885242bf6a24b59bbbc647.jpeg"),
    description: "Вместительная сумка из телячьей замши. Пара прочных трубчатых ручек и удлиненные ручки под гладкую кожу контрастного цвета. Одно отделение с внутренним плоским карманом. На подкладке. Магнитная застежка. Размер: 47 х 14,5 х 42 см (длина х ширина х высота).",
    sizeChart: "one_size",
    sizes: ["One size"],
  },
  {
    id: "lime-men-33392",
    gender: "men",
    title: "Сумка из замши с плечевым ремнем",
    category: "Рюкзаки и аксессуары",
    price: 17999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/fae3da89a7de5068afabf50a28fe9ec6.jpeg"),
    description: "Вместительная сумка из мягкой замши. Пара плечевых ручек. Съемный регулируемый ремень в комплекте. Одно отделение с внутренним карманом на молнии и двумя открытыми карманами. На подкладке. Застегивается металлической молнией с пуллером. Размер: 48 х 14 х 34 см (длина х ширина х в",
    sizeChart: "one_size",
    sizes: ["One size"],
  },
  {
    id: "lime-men-32979_6809_680",
    gender: "men",
    title: "Солнцезащитные очки в ацетатной оправе",
    category: "Рюкзаки и аксессуары",
    price: 3999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/d9d8525bc25053119d38657e1625d2b3.jpeg"),
    description: "Универсальные очки в легкой оправе из прочного и экологичного ацетата. Дополнены металлическими элементами на широких дужках. Модель с UV-защитой от солнца и затемненными линзами. В комплект входят футляр и салфетка из микрофибры.",
    sizeChart: "one_size",
    sizes: ["One size"],
  },
  {
    id: "lime-men-32766_6808_681",
    gender: "men",
    title: "Солнцезащитные очки в овальной оправе",
    category: "Рюкзаки и аксессуары",
    price: 3999,
    image: u("https://cache-limeshop.cdnvideo.ru/limeshop/aa/636cb02112785bc590c74730cc4c817f.jpeg"),
    description: "Очки овальной формы выполнены из ацетата с анималистичным паттерном. Затемненные линзы с UV-защитой от солнца. В комплект входят футляр и салфетка из микрофибры.",
    sizeChart: "one_size",
    sizes: ["One size"],
  },
];

window.CATALOG_PRODUCTS = WOMEN.concat(MEN);

window.CatalogApi = {
  all() {
    return window.CATALOG_PRODUCTS || [];
  },
  byGender(g) {
    return this.all().filter((p) => p.gender === g);
  },
  find(id) {
    return this.all().find((p) => p.id === id) || null;
  },
  /** women | men */
  normalizeGender(g) {
    return g === "men" ? "men" : "women";
  },
  /** из URL, sessionStorage или women */
  currentGender() {
    try {
      const path = (location.pathname || "").split("/").pop() || "";
      if (path === "catalog.html" || path === "product.html") {
        const q = new URLSearchParams(location.search).get("gender");
        if (q === "men" || q === "women") {
          sessionStorage.setItem("volna_gender", q);
          return q;
        }
      }
      const s = (() => {
        let v = sessionStorage.getItem("volna_gender");
        if (v === "men" || v === "women") return v;
        const old = sessionStorage.getItem("polosa_gender") || sessionStorage.getItem("zhenya_gender");
        if (old === "men" || old === "women") {
          sessionStorage.setItem("volna_gender", old);
          sessionStorage.removeItem("polosa_gender");
          sessionStorage.removeItem("zhenya_gender");
          return old;
        }
        return null;
      })();
      if (s === "men" || s === "women") return s;
    } catch (_) {}
    return "women";
  },
  setGender(g) {
    const v = this.normalizeGender(g);
    try {
      sessionStorage.setItem("volna_gender", v);
    } catch (_) {}
    return v;
  },
  async hydrateFromServer() {
    try {
      if (location.protocol !== "http:" && location.protocol !== "https:") return false;
      const url =
        typeof window.volnaApiUrl === "function" ? window.volnaApiUrl("/api/products") : "/api/products";
      const res = await fetch(url);
      const text = await res.text();
      let data = {};
      if (text) {
        try {
          data = JSON.parse(text);
        } catch {
          return false;
        }
      }
      if (!res.ok || !Array.isArray(data.products)) return false;
      window.CATALOG_PRODUCTS = data.products;
      try {
        window.dispatchEvent(new CustomEvent("volna:catalog"));
      } catch (_) {}
      return true;
    } catch {
      return false;
    }
  },
};
